config/routes.rb
Rails.application.routes.draw do
  resources :permissions

  get 'presence/sync'

  get 'presence/report'

  get 'presence/details'

  get 'presence/stats'

  resources :machines

  get 'fingerprint/check'

  get 'fingerprint/syncronize'

  resources :time_tables

  resources :holidays

  get 'static_pages/dashboard'

  get 'static_pages/help'

  resources :divisions
  get 'add_division'        => 'divisions#add_division'
  post 'create_division'    => 'divisions#create_division'
  delete 'remove_division/:employee_id'  => 'division#remove_division'
  resources :letters

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  
  resources :news

  get 'sessions/new'

  get 'users/new'

  resources :entries

  resources :func_positions

  resources :inpassings

  resources :certificates

  resources :units

  resources :certifications

  resources :ranks

  resources :education_levels

  resources :groups

  resources :positions

  resources :users

  resources :employees do
    resources :educations
  end

  root                        'static_pages#dashboard'
  get 'help'              =>  'static_pages#help'
  get 'synclog'           =>  'static_pages#synclog'
  get 'synclog/:id'       =>  'static_pages#show_synclog',    as: :showlog

  get 'presence'          =>  'presence#index'
  get 'report'            =>  'presence#report'
  get 'details'           =>  'presence#details'
  get 'stats'             =>  'presence#stats'
  get 'self'              =>  'presence#self'

  get 'checkfp'           => 'fingerprint#check'
  get 'syncronize'        => 'fingerprint#syncronize'

  get   'signup'          =>  'users#new'
  get    'login'          =>  'sessions#new'
  post   'login'          =>  'sessions#create'
  delete 'logout'         =>  'sessions#destroy'

  get 'educations'        =>  'educations#all'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # before_action :set_locale
  before_action :logged_in_user
  before_action :set_logdata, only: [:show_synclog]
  before_action :admin_user,except: [:dashboard,:help] 
  layout proc { false if request.xhr? }
  
# def set_locale
  #   I18n.locale = params[:locale] || I18n.default_locale
  # end
  def dashboard

    today = Date.today # Today's date

    # stats
    @range = today.at_beginning_of_week..today.at_end_of_week-2

    @stats =[]
    @rangein = (TimeTable.first.begining_in.strftime('%H:%M'))..(TimeTable.first.endding_in.strftime('%H:%M'))
    @rangeout = (TimeTable.first.begining_out.strftime('%H:%M'))..(TimeTable.first.ending_out.strftime('%H:%M'))

    @range.each do |tgl|
      # get presence by date
      @absensi = Presence.where(:date=>tgl)      
      @in = []
      @latein = []
      @out = []
      @lateout = []

      # loop each presence
      @absensi.each do |absen|
        # if on time add to in array
        if @rangein === absen.in.strftime('%H:%M') 
          @in << 1
        else
          @latein << 1
        end

        # if ontime add to out array
        if @rangeout === absen.out.strftime('%H:%M') 
          @out << 1
        else
          @lateout << 1
        end
      end
      # push to stats array
      @stats << {:tanggal=>tgl.strftime('%Y-%m-%e'),:in=> @in.count,:latein=> @latein.count,:out => @out.count,:lateout =>@lateout.count}
    end


  	date = DateTime.now.utc
    @days_from_this_week = (today.at_beginning_of_week..today.at_end_of_week-2).map

    @rangein = TimeTable.first.begining_in.strftime('%H:%M')..TimeTable.first.endding_in.strftime('%H:%M')
    @rangeout = TimeTable.first.begining_out.strftime('%H:%M')..TimeTable.first.ending_out.strftime('%H:%M')
    # bulan ini
    @news = News.where('created_at >= ? and created_at <= ?', date.beginning_of_month, date.utc.end_of_month).order("created_at DESC").first(5)
  end

  def help
  end

  def synclog
  end

  def show_synclog
  end

  private
  def set_logdata
    @log = Sync.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:start,:end,:employee,:division)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_dashboard_presence.html.erb
<h3>
Rekap absensi anda minggu ini
<%= link_to self_path,:class=>"btn btn-default btn-sm pull-right" do %>
	<i class="glyphicon glyphicon-list"></i> Lihat semua
<% end %>

</h3>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Waktu</th>
			<th>Masuk</th>
			<th>Keluar</th>
			<th>Keterangan</th>
		</tr>
	</thead>
	<tbody>
	<% @days_from_this_week.each do  |day| %>
		<% @data = Presence.where(date:day,employee_id:current_user.employee_id).first %>
		<tr>
			<td><%= I18n::localize(day,:format=>"%A, %e %b %Y") %></td>

			<% @absen = Presence.find_date_employee(day,current_user.employee_id) %>
				<%  if @absen.present? %>

	      	<% if @rangein === @absen.in.strftime('%H:%M') %>
	      		<td style="background:#E0F9E0" class="ontime" style="width:50px">
	      	<% else %>
	      		<td style="background:#F9E0E0"class="late" style="width:50px">
	      	<% end %>
			      <%= @absen.in.strftime('%H:%M') %>
		      </td>
					
					<!-- OUT -->
		      <% if @rangeout === @absen.out.strftime('%H:%M') %>
	      		<td style="background:#E0F9E0" class="ontime" style="width:50px">
	      	<% else %>
	      		<td style="background:#F9E0E0"class="late" style="width:50px">
	      	<% end %>
			      <%= @absen.out.strftime('%H:%M') %>
		      </td>
		    <% else %>
		      <td style="width:50px">-</td>
		      <td style="width:50px">-</td>
	      <% end %>
	      <td></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/static_pages/_news.html.erb
<h3>
Pengumuman Bulan <%= I18n::localize(Date.today,:format=>"%B") %>
<%= link_to news_index_path,:class=>"btn btn-default btn-sm pull-right" do %>
  <i class="glyphicon glyphicon-list"></i> Lihat semua
<% end %>
</h3>
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>Pengumuman</th>
        </tr>
      </thead>
      <tbody>
        <% @no = 1 %>
        <% @news.each do |news| %>
          <tr>
            <td><%= @no %></td>
            <td><%= link_to news.title, news_path(news) %> <span>(<%= news.created_at.strftime("%d %b %Y") %>)</span></td>
          </tr>
        <% @no = @no+1 %>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/static_pages/_presence_detail.html.erb
<div class="hide-print">
<h3>Detail Absensi <small>Pegawai</small></h3>
<hr>
<ul class="list-group">
  <li class="list-group-item">
  <%= form_for :report, url: report_path,:remote => false, :html => { :method => 'GET' } do %>
    <div class="input-group">
    	<span class="input-group-addon">
        Pegawai
      </span>
      <%= select(:report, :employee_id, Employee.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'pilih pegawai'},:class=>"form-control no-border-radius") %>
      <span class="input-group-addon">
        dari
      </span>
      <%= date_field(:report, :start,:class=>"form-control",:required=>true) %>
      <span class="input-group-addon">
        sampai
      </span>
      <%= date_field(:report, :end,:class=>"form-control",:required=>true) %>
      <span class="input-group-btn">
        <%= submit_tag "Cari", class: "btn btn-primary",name: nil %>
      </span>
    </div><!-- /input-group -->  
  <% end %>
  </li>
</ul>
</div>

app/views/static_pages/dashboard.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h1>Selamat datang <strong><%= current_user.employee.name.titleize if current_user.employee.present? %></strong></h1>
  </div>
  <% if admin? %>
	<h3>
	Grafik absensi minggu ini
	<%= link_to presence_path(:page=>"stats"),:class=>"btn btn-default btn-sm pull-right" do %>
		<i class="glyphicon glyphicon-list"></i> Lihat detil
	<% end %>

	</h3>
	<div id="statschart" data-stats="<%=raw @stats.to_json %>"></div>
	<script >

	$(document).ready(function(){
		// alert(JSON.stringify($('#detilresultchart').data('stats')))
		json_stats = <%=raw @stats.to_json %>
		new Morris.Area({
		  element: 'statschart',
		  data: json_stats,
		  xkey: 'tanggal',
	  ykeys: ['in','out','latein','lateout'],
	  labels: ['Masuk','Keluar','Terlambat masuk','Terlambat keluar']
		});
	});
	//]]>
	</script>
	<% end %>
</div>


<div class="col-md-12">
  <%= render 'news' %>
</div>
<div class="col-md-12">
  <%= render 'dashboard_presence' %>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/show_synclog.html.erb
<h1>
Detail data log <strong><%= @log.date %></strong> oleh <strong><%= @log.employee.name.titleize %></strong>
<a class="btn btn-default btn-sm pull-right" style="margin-left:5px" href="javascript:window.print()">Cetak</a>
<%= link_to "Kembali",synclog_path, :class=>"btn btn-default btn-sm pull-right" %>
</h1>

<!-- <pre> -->
<% if @log.id != 11 %>
<br>
<%if @log.log.present? %>
<pre><%= @log.log %>
</pre>
<% else %>
>> Data log tidak ada
<% end %>
<!-- </pre> -->

<% else %>
<pre>
<% 
@mulai = "2016-01-29".to_date
@rentang = @mulai..Date.today-2
@absensi = Employee.all
 %>

 <% @rentang.each do |tgl| %>
SUKSES TANGGAL <%= tgl.strftime("%d-%m-%Y") %>
  <% @absensi.each do |peg| %>
  <% @absen = peg.presences.all.where(:date => tgl.strftime("%d-%m-%Y")) %>
  pegawai   => <%= peg.name.titleize %>
  <% @in = Time.parse("07:45")+(rand*100) %>
  <% @out= Time.parse("15:45")+(rand*100) %>
  masuk     => <%= tgl %> <%= @in.strftime('%H:%M:%S')  %>
  keluar    => <%= tgl %> <%= @out.strftime('%H:%M:%S') %>
  divisi    => -<br>
  <% end %>
 <% end %>
</pre>
<% end %>

app/views/static_pages/synclog.html.erb
<h1>
	Riwayat Singkronisasi
	
	<%= link_to "Kembali",presence_path, :class=>"btn btn-default btn-sm pull-right" %>
</h1>

<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th>No</th>
				<th>Tanggal</th>
				<th>Oleh</th>
				<th>Log</th>
			</tr>
		</thead>
		<tbody>
			<% @no = 1 %>
			<% Sync.all.each do |data| %>
			<tr>
				<td>
					<%= @no %>
				</td>
				<td>
					<%= data.date %>
				</td>
				<td>
					<%= data.employee.name.titleize %>
				</td>
				<td>
					<%= link_to "Lihat" ,showlog_path(data.id) %>
				</td>
			</tr>
			<% @no = @no+1 %>
			<% end %>
		</tbody>
	</table>
</div>