config/routes.rb
Rails.application.routes.draw do
  resources :permissions

  get 'presence/sync'

  get 'presence/report'

  get 'presence/details'

  get 'presence/stats'

  resources :machines

  get 'fingerprint/check'

  get 'fingerprint/syncronize'

  resources :time_tables

  resources :holidays

  get 'static_pages/dashboard'

  get 'static_pages/help'

  resources :divisions
  get 'add_division'        => 'divisions#add_division'
  post 'create_division'    => 'divisions#create_division'
  delete 'remove_division/:employee_id'  => 'division#remove_division'
  resources :letters

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  
  resources :news

  get 'sessions/new'

  get 'users/new'

  resources :entries

  resources :func_positions

  resources :inpassings

  resources :certificates

  resources :units

  resources :certifications

  resources :ranks

  resources :education_levels

  resources :groups

  resources :positions

  resources :users

  resources :employees do
    resources :educations
  end

  root                        'static_pages#dashboard'
  get 'help'              =>  'static_pages#help'
  get 'synclog'           =>  'static_pages#synclog'
  get 'synclog/:id'       =>  'static_pages#show_synclog',    as: :showlog

  get 'presence'          =>  'presence#index'
  get 'report'            =>  'presence#report'
  get 'details'           =>  'presence#details'
  get 'stats'             =>  'presence#stats'
  get 'self'              =>  'presence#self'

  get 'checkfp'           => 'fingerprint#check'
  get 'syncronize'        => 'fingerprint#syncronize'

  get   'signup'          =>  'users#new'
  get    'login'          =>  'sessions#new'
  post   'login'          =>  'sessions#create'
  delete 'logout'         =>  'sessions#destroy'

  get 'educations'        =>  'educations#all'

  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	mount_uploader :id_pic, PictureUploader
	mount_uploader :fam_pic, PictureUploader

	validates :nik, 	presence: {message:"Kolom NIK harus diisi"},
						uniqueness: { case_sensitive: false,message: "kolom NIK sudah terdaftar, silahkan masukan NIK yang lain"}

	validates :name, 	presence: {message:"Kolom nama harus diisi"}, 
						uniqueness: { case_sensitive: false,message: "kolom nama sudah terdaftar, silahkan pilih user yang lain"}

	# validates :id_num, 	presence: {message:"Kolom nomor KTP harus diisi"}, 
						# uniqueness: { case_sensitive: false,message: "kolom nomor KTP sudah terdaftar, silahkan pilih no KTP yang lain"}
	
	# validates :mail, 	presence: {message:"Kolom nomor email harus diisi"}, 
	# 					uniqueness: { case_sensitive: false,message: "kolom email sudah terdaftar, silahkan pilih email yang lain"}
	has_one  :user
	has_many :entries
	has_many :educations
	has_many :ranks
	has_many :certifications
	has_many :units
	has_many :certificates
	has_many :inpassings
	has_many :news
	has_many :syncronizes
	has_many :synces
	has_many :presences
	has_many :permissions

	belongs_to :division
	# mount_uploader :picture, PictureUploader

	before_save :huruf_kecil

	def huruf_kecil
		self.name = self.name.downcase
		# self.birhtplace = self.birhtplace.downcase
	end

	def self.find_division(division)
      @result = self.where(:division_id => division)
      return @result
   end

  def barcode
    @style = "<style media=\"all\" type=\"text/css\">
      table.barby-barcode { border-spacing:0;float:right;margin-bottom:15px}
      tr.barby-row {}
      td.barby-cell { width: 3px !important; height: 50px !important; }
      td.barby-cell.on { background: #000 !important; }</style>"
    @code = self.nik
    @generate_code = Barby::Code128.new(@code)
    @barcode_html = Barby::HtmlOutputter.new(@generate_code)
    @output = @style + @barcode_html.to_html
    @output.html_safe
  end
	

	# has_one :group
  	# has_one :position

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :logged_in_user
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html
  
  def index
    # @employees = Employee.all
    if params[:q]
      @employees = Employee.where("name LIKE ? OR nik LIKE ?","%#{params[:q]}%","%#{params[:q]}%")if params[:q]
    
    else
      @employees = Employee.all
    end
    respond_with(@employees)
  end

  def show
    @title = "#{@employee.name.titleize}-#{@employee.nik}"
    # respond_with(@employee)
  end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:success]= "Data pegawai berhasil di tambah"
      redirect_to action: "index"
    else
      respond_with(@employee)
    end
    # redirect_to action: "index"
  end

  def update
    @employee.update(employee_params)
    respond_with(@employee)
  end

  def destroy
    @employee.destroy
    respond_with(@employee)
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:nik,:name, :birhtplace, :birthdate, :phone, :mobile, :mail, :status,:picture,:id_num,:id_pic,:fam_pic,:address,:front_title,:back_title,:group_id,:position_id,:division_id,:admin)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_data_certificate.html.erb
<div class="table-responsive">
  <table class="table" id="certificateData">
    <thead>
      <tr>
        <th>No</th>
        <th>Pegawai</th>
        <th>Tema</th>
        <th>Tahun</th>
        <% if admin? or current_user.employee.id == @employee.id  %>
        <th>Dokumen</th>
        <% end %>
        <% if admin? %>
        <th colspan="3"></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @no = 1 %>
      <% @employee.certificates.each do |certificate| %>
        <tr id="certificate_<%= certificate.id %>">
          <td><%= @no %></td>
          <td><%= certificate.employee.name.titleize %></td>
          <td><%= certificate.theme %></td>
          <td><%= certificate.year %></td>
          
          <% if admin? or current_user.employee.id == @employee.id  %>
          <td>
            <% if certificate.document.present? %>
              <a href="<%= certificate.document %>" target="_blank"style="color:green !important">Ada</a>
            <% else %>
              <div style="color:red">tidak ada</div>
            <% end %>
          </td>
          <% end %>
          <% if admin? %>
          <td><%= link_to 'Edit', edit_certificate_path(certificate),:class=>"edit edit_certificate",data: {remote: true,disable_with: "proses..."} %></td>
          <td><%= link_to 'Hapus', certificate, method: :delete, data: { confirm: 'Ciyus mau di hapus?' },:class=>"destroy destroy_certificate", data: {remote: true, confirm: 'Ciyus mau di hapus?' ,disable_with: "proses..."} %></td>
          <% end %>
        </tr>
        <% @no = @no + 1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/_data_certification.html.erb
<div class="table-responsive">
  <table class="table"id="certificationData">
    <thead>
      <tr>
        <th>No</th>
        <th>No. Sertifikat</th>
        <th>No. Registrasi</th>
        <th>Tahun</th>
         <% if admin? or current_user.employee.id == @employee.id  %>
        <th>Dokumen</th>
        <% end %>

        <% if admin? %>
        <th colspan="3"></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @no = 1 %>
      <% @employee.certifications.each do |certification| %>
        <tr id="certification_<%= certification.id %>">
          <td><%= @no %></td>
          <td><%= certification.certificate_number %></td>
          <td><%= certification.reg_number %></td>
          <td><%= certification.year %></td>
          
           <% if admin? or current_user.employee.id == @employee.id  %>
          <td>
            <% if certification.document.present? %>
              <a href="<%= certification.document %>"target="_blank"style="color:green !important">Ada</a>
            <% else %>
              <div style="color:red">tidak ada</div>
            <% end %>
          </td>
          <% end %>

          <% if admin? %>
          <td class="hide_print">
            <%= link_to 'Edit',edit_certification_path(certification), :class=> 'edit edit_certification', data: {remote: true,disable_with: "proses..."} %>
            <%= link_to 'Hapus', certification, method: :delete, data: {remote: true, confirm: 'Ciyus mau di hapus?' ,disable_with: "proses..."} , :class=>"destroy destroy_certification" %>
          </td>
          <% end %>
        </tr>
        <% @no = @no + 1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/_data_education.html.erb
<div class="table-responsive">
  <table class="table" id="educationData">
    <thead>
      <tr>
        <th>No</th>
        <th>Jenjang</th>
        <th>No Surat Perjanjian</th>
        <th>Unit Pendidikan</th>
        <th>Jurusan</th>
        <th>Tahun Lulus</th>
        <% if admin? || current_user.employee.id == @employee.id %>
        <th>Dokumen</th>
        <% end %>
        <% if admin? %>
        <td></td>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @no = 1 %>
      <% @employee.educations.each do |pend| %>
      <tr id="education_<%= pend.id %>">

        <td><%= @no%> </td>
        <td>
          <% if pend.education_level_id.present? %>
            <%= pend.education_level.name %>
          <% else %>
            -----
          <% end %>
        </td>
        
        <td><%= pend.number %></td>
        <td><%= pend.graduate %></td>
        <td><%= pend.departement %></td>
        <td><%= pend.year %></td>
        <% if admin? or current_user.employee.id == @employee.id %>

        <td>
          <% if pend.document.present? %>
            <a href="<%= pend.document %>"target="_blank"style="color:green !important"data-image="<%= pend.document_url %>">Ada</a>
          <% else %>
            <div style="color:red">Tidak ada</div>
          <% end %>
        </td>
        <% end %>
         <% if admin? %>
        <td class="hide_print">
          <%= link_to 'Edit', edit_employee_education_path(@employee,pend) ,:class=>"edit edit_education",data: {remote: true,disable_with: "proses..."}%>
          <%= link_to 'Hapus', employee_education_path(@employee,pend), method: :delete, :class=>"destroy hapus_education",data: {remote: true, confirm: 'Ciyus mau di hapus?' ,disable_with: "proses..."} %></td>
        </td>
        <% end %>
      </tr>
      <% @no = @no +1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/_data_entry.html.erb
<div class="table-responsive">
  <table class="table" id="entryData">
    <thead>
      <tr>
        <th>No</th>
        <th>Tetap</th>
        <th>Kontrak </th>
        <th>No SK</th>
         <% if admin? %>
        <th>
          Dokumen
        </th>
        <th colspan="3"></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @no = 1 %>
      <% @employee.entries.each do |entry| %>
        <tr id="entry_<%= entry.id %>">
          <td><%= @no %></td>
          <td><%= entry.fixed %></td>
          <td><%= entry.contract %></td>
          <td><%= entry.number %></td>
           <% if admin? %>
          <td>
            <% if entry.document.present? %>
              <a href="<%= entry.document %>" target="_blank"style="color:green !important" data-image="<%= entry.document_url %>">Ada</a>
            <% else %>
              <div style="color:red">Tidak ada</div>
            <% end %>
          </td>
          <td><%= link_to 'Edit', edit_entry_path(entry),:class=>"edit",data: {remote: true,disable_with: "proses..."} %></td>
          <td><%= link_to 'Hapus', entry, method: :delete,:class=>"destroy destroy_entry",data: {remote: true, confirm: 'Ciyus mau di hapus?' ,disable_with: "proses..."} %></td>
          <% end %>
        </tr>
        <% @no = @no+1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/_data_inpassing.html.erb
<div class="table-responsive">
  <table class="table" id="inpassingData">
    <thead>
      <tr>
        <th>No</th>
        <th>Nomor SK</th>
        <th>Jabatan </th>
        <th>NIDN/NIPN</th>
        <% if admin? or current_user.employee.id == @employee.id  %>
        <th>
          Dokumen
        </th>
        <% end %>
        <% if admin? %>
        <th colspan="3"></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @no = 1 %>
      <% @employee.inpassings.each do |inpassing| %>
        <tr id="inpassing_<%= inpassing.id %>">
          <td><%= @no %></td>
          <td><%= inpassing.number %></td>
          <td><%= inpassing.func_position.name if inpassing.func_position_id.present? %></td>
          <td><%= inpassing.lecture_number %></td>

          <% if admin? or current_user.employee.id == @employee.id  %>
          <td>
            <% if inpassing.document.present? %>
              <a href="<%= inpassing.document %>" target="_blank"style="color:green !important" data-image="<%= inpassing.document_url %>">Ada</a>
            <% else %>
              <div style="color:red">Tidak ada</div>
            <% end %>
          </td>
          <% end %>

          <% if admin? %>
          <td><%= link_to 'Edit', edit_inpassing_path(inpassing),:class=>"edit",data: {remote: true,disable_with: "proses..."} %></td>
          <td><%= link_to 'Hapus', inpassing, method: :delete,:class=>"destroy destroy_inpassing",data: {remote: true, confirm: 'Ciyus mau di hapus?' ,disable_with: "proses..."} %></td>
          <% end %>
        </tr>
        <% @no = @no+1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/_data_rank.html.erb
<div class="table-responsive">
  <table class="table" id="ranksData">
    <thead>
      <tr>
        <th>No</th>
        <th>No SK</th>
        <th>Golongan</th>
        <th>Tahun</th>
        <% if admin? or current_user.employee.id == @employee.id %>
        <th>Dokumen</th>
        <% end %>
        <% if admin? %>
        <td></td>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @no = 1 %>
      <% @employee.ranks.each do |pangkat| %>
      <tr id="rank_<%= pangkat.id %>">
        
        <td><%= @no%> </td>
        <td>
          <%= pangkat.number %>
        </td>
        
        <td><%= pangkat.group.name if pangkat.group_id.present? %></td>
        <td><%= pangkat.year %></td>

        <% if admin? or current_user.employee.id == @employee.id %>
        <td>
          <% if pangkat.document.present? %>
            <a href="<%= pangkat.document %>" target="_blank" style="color:green !important" data-image="<%= pangkat.document_url %>">Ada</a>
          <% else %>
            <div style="color:red">Tidak ada</div>
          <% end %>
        </td>
        <% end %>

        <% if admin? %>
        <td class="hide_print">
          <%= link_to 'Edit', edit_rank_path(pangkat) ,:class=>"edit edit_rank",data: {remote: true,disable_with: "proses..."}%>
          <%= link_to 'Hapus', rank_path(pangkat), method: :delete, :class=>"destroy hapus_rank",data: {remote: true, confirm: 'Ciyus mau di hapus?' ,disable_with: "proses..."} %></td>
        </td>
        <% end %>
      </tr>
      <% @no = @no +1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/_data_unit.html.erb
<div class="table-responsive">
  <table class="table"id="unitData">
  <thead>
    <tr>
      <th>No</th>
      <th>Pegawai</th>
      <th>Jabatan</th>
      <th>No. SK</th>
      <th>Masa jabatan</th>
      <% if admin? or current_user.employee.id == @employee.id  %>
      <th>Dokumen</th>
      <% end %>
      <% if admin? %>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @no = 1 %>
    <% @employee.units.each do |unit| %>
      <tr id = "unit_<%= unit.id %>">
        <td><%= @no %></td>
        <td><%= unit.employee.name.titleize %></td>
        <td><%= unit.position.name %></td>
        <td><%= unit.number %></td>
        <td><%= unit.date_start.year %> - <%= unit.date_end.year %></td>
        <% if admin? or current_user.employee.id == @employee.id  %>
        <td>
          <% if unit.document.present? %>
            <a href="<%= unit.document %>" style="color:green !important" target="_blank">Ada</a>
          <% else %>
            <div style="color:red">tidak ada</div>
          <% end %>
        </td>
        <% end %>
        <% if admin? %>
        <td><%= link_to 'Edit', edit_unit_path(unit),:class=>"edit edit_unit",data: {remote: true,disable_with: "proses..."} %></td>
        <td><%= link_to 'Hapus', unit, method: :delete,:class=>"destroy destroy_unit",data: {remote: true, confirm: 'Ciyus mau di hapus?' ,disable_with: "proses..."}  %></td>
        <% end %>
      </tr>
      <% @no = @no +1 %>
    <% end %>
  </tbody>
</table>

</div>

app/views/employees/_form_education.html.erb
<!-- Modal -->
<div class="modal fade" id="modalEducation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Tambah Data Pendidikan</h4>
      </div>
      <div class="modal-body">
        <%= form_for([@employee, Education.new], :html => {:multipart => true} , remote: true) do |f| %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
          <div class="form-group">
            <%= f.label :education_level_id, "Jenjang Pendidikan" %>
            <%= f.collection_select(:education_level_id,EducationLevel.all,:id,:name,{:prompt => 'pilih jenjang'}, :class=>"form-control")%>
          </div>
          <div class="form-group">
            <%= f.label :number,"Nomor Surat Perjanjian Dinas" %><br>
            <%= f.text_field :number,:class => "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :graduate ,"Nama Unit Pendidikan"%><br>
            <%= f.text_field :graduate,:class => "form-control"  %>
          </div>
           <div class="form-group">
            <%= f.label :departement ,"Jurusan/Program"%><br>
            <%= f.text_field :departement,:class => "form-control"  %>
          </div>
          <div class="form-group">
            <%= f.label :year , "Tahun"%><br>
            <%= f.date_select :year ,:class => "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :document, "Dokumen" %>
            <%= f.file_field :document ,:class=>"form-control"%>
          </div>
          
      </div>
      <div class="modal-footer">
          <%= f.submit "Tambah",:class=>"btn btn-primary",data: { disable_with: "Prosess..." } %>
        <% end %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
      </div>
    </div>
  </div>
</div>

app/views/employees/_search.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for :employee, url: employees_path, :html => { :method => 'GET' } do %>
      <div class="input-group pull-right">
        <span class="input-group-addon">
          Cari pegawai
        </span>
        <%= text_field_tag :q,nil,class: "form-control",placeholder: "Kata kunci berupa Nama / NIK" %>
        <span class="input-group-btn">
          <%= submit_tag "Cari", class: "btn btn-primary",name: nil %>
        </span>
      </div><!-- /input-group -->  
    <% end %>
  </div>
</div>

app/views/employees/edit.html.erb
<h1>Edit Data</h1>

<%= render 'form' %>


<% if current_user.admin? %>

<% end %>

<div class="pull-right">
	<%= link_to 'Tampil', @employee %> |
	<%= link_to 'Kembali', employees_path %>
</div>

app/views/employees/index.html.erb
<div class="row">
  
  <div class="col-md-12">
    <h3>
      Data Pegawai
      <% if admin? %>
      <%= link_to 'Unduh barcode', new_employee_path,:class => "btn btn-sm btn-primary pull-right",:style=>"margin-left:5px" %>
      <%= link_to 'Tambah Pegawai', new_employee_path,:class => "btn btn-sm btn-primary pull-right" %>
      <% end %>
    </h3>
    <hr>
    <%= render 'search' %>

    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>No</th>
            <th>Id</th>
            <th>Nama</th>
            <th>NIK</th>
            <th>HP</th>
            <th>Telp</th>
            <% if admin? %>
            <th>Status</th>
            <th colspan="3"></th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <% @no = 1 %>
          <% @employees.each do |employee| %>
            <tr>
              <td><%= @no %></td>
              <td><%= employee.id %></td>
              <td><%= link_to employee.name.titleize, employee %></td>
              <td><%= employee.nik %></td>
              <td><%= employee.phone %></td>
              <td><%= employee.mobile %></td>
              
              <% if admin? %>
              <td>
                <% if employee.status == false %>
                  Tidak Aktif
                <% else %>
                  Aktif
                <% end %>
              </td>
              <td></td>
              <td><%= link_to 'Edit', edit_employee_path(employee) ,:class=>"edit"%></td>
              <td><%= link_to 'Hapus', employee, method: :delete, :class=>"destroy",data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
            <% @no = @no + 1 %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>



<br>

app/views/employees/new.html.erb
<h1>Tambah Data Pegawai</h1>

<%= render 'form' %>
<br>
<%= link_to 'Kembali', employees_path,:class=>"pull-right" %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<!-- <div class="print top">
  Cetak data : <%= @employee.name.titleize %> | NIK : <%= @employee.nik %>
  <div class="pull-right">
    <%= Date.today %>
  </div>
</div> -->
<div class="row">
  <div class="col-sm-8">
    <h3 style="font-size:36px;margin-top:0"><%= @employee.name.titleize %></h3>
    <p>
      <strong>ID:</strong>
      <%= @employee.id %>
    </p>
    <p>
      <strong>Nomor Indok Pegawai:</strong>
      <%= @employee.nik %>
    </p>
    <p>
      <strong>Nomor KTP:</strong>
      <%= @employee.id_num %>
    </p>
    <p>
      <strong>Gelar Depan:</strong>
      <%= @employee.front_title %>
    </p>
    <p>
      <strong>Gelar Belakang:</strong>
      <%= @employee.back_title %>
    </p>
    <p>
      <strong>Tempat Lahir:</strong>
      <%= @employee.birhtplace %>
    </p>

    <p>
      <strong>Alamat:</strong>
      <%= @employee.address %>
    </p>


    <p>
      <strong>Tanggal Lahir:</strong>
      <%= @employee.birthdate %>
    </p>

    <p>
      <strong>Telp:</strong>
      <%= @employee.phone %>
    </p>

    <p>
      <strong>HP:</strong>
      <%= @employee.mobile %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @employee.mail %>
    </p>
    <h3>Status Kepegawaian</h3>
    <p>
      <strong>Status:</strong>
      <%= @employee.status %>
    </p>
  </div>
  <div class="col-sm-4" style="text-align:right;float:right;position: absolute;right: 0;top: 0;">
    <%= @employee.barcode %>
    <br><br>
    <% if @employee.picture.present? %>

    <%= image_tag(@employee.picture_url, :width => 150) if @employee.picture.present? %>
    <% end %>
  </div>
</div>


<div class="row">
  <!-- lampiran -->
  <div class="col-xs-12">
    <h3>Lampiran</h3>
    <br>
    <table class="table">
      <tr>
        <td>
          KTP
        </td>
        <td>
          <% if @employee.id_pic.present? %>
             <a href="<%= @employee.id_pic %>" target="_blank" style="color:green !important">ada</a>
          <% else %>
            <div style="color:red">tidak ada</div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Kartu Keluarga</td>
        <td>
          <% if @employee.fam_pic.present? %>
            <a href="<%= @employee.fam_pic %>" target="_blank" style="color:green !important">ada</a>
          <% else %>
            <div style="color:red">tidak ada</div>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <!-- sertifikat -->
  <div class="col-xs-12 units">
    <h3>
      TMT
      <% if current_user.admin? %>
      <%= link_to 'Tambah Data', new_entry_path,:class=>"pull-right btn btn-xs btn-primary",:id=>"add_entry" ,:remote => true ,data: { disable_with: "Prosess...", id:"#{@employee.id}" } %>
      <% end %>
    </h3>
    <div class="entry_add_content"></div>
    <%= render 'data_entry' %>
  </div>
  <!-- pendidikan -->
  <div class="col-xs-12 education">
    <h3>
      Pendidikan
      <% if current_user.admin? %>
      
      <%= link_to "Tambah pendidikan", new_employee_education_path(@employee) ,:remote => true ,:id=> "add_education",:class=> "pull-right btn btn-xs btn-primary",data: { disable_with: "Prosess...", id:"#{@employee.id}" }%>
      <% end %>
    </h3>

    <%= render 'form_education' %>
    <div class="education_add_content"></div>
    <%= render :partial => "data_education" %>
  </div>

  <!-- .kepangkatan -->
  <div class="col-xs-12 kepangkatan">
    <h3>
      Kepangkatan
      <% if current_user.admin? %>
      <%= link_to 'Tambah Pangkat', new_rank_path,:class=>"pull-right btn btn-xs btn-primary",:id=>"add_rank" ,:remote => true ,data: { disable_with: "Prosess...", id:"#{@employee.id}" } %>
      <% end %>

    </h3>

    <div class="rank_add_content"></div>
    <%= render 'data_rank' %>
  </div>

  <!-- Jabatan fungsional/inpassing -->
  <div class="col-xs-12 kepangkatan">
    <h3>
      Jabatan Fungsional/Inpassing
      <% if current_user.admin? %>
      <%= link_to 'Tambah Inpassing', new_inpassing_path,:class=>"pull-right btn btn-xs btn-primary",:id=>"add_inpassing" ,:remote => true ,data: { disable_with: "Prosess...", id:"#{@employee.id}" } %>
      <% end %>
    </h3>

    <div class="inpassing_add_content"></div>
    <%= render 'data_inpassing' %>
  </div>

  <!-- .sertifikat -->
  <div class="col-xs-12 certifications">
    <h3>
      Sertifikasi Dosen
      <% if current_user.admin? %>
      <%= link_to 'Tambah Sertifikasi Dosen', new_certification_path,:class=>"pull-right btn btn-xs btn-primary",:id=>"add_certification" ,:remote => true ,data: { disable_with: "Prosess...", id:"#{@employee.id}" } %>
      <% end %>
    </h3>

    <div class="certification_add_content"></div>
    <%= render 'data_certification' %>
  </div>

  <!-- unit kerja -->
  <div class="col-xs-12 units">
    <h3>
      Unit Kerja
      <% if current_user.admin? %>
      <%= link_to 'Tambah Unit Kerja', new_unit_path,:class=>"pull-right btn btn-xs btn-primary",:id=>"add_unit" ,:remote => true ,data: { disable_with: "Prosess...", id:"#{@employee.id}" } %>
      <% end %>
    </h3>
    <div class="unit_add_content"></div>
    <%= render 'data_unit' %>
  </div>

  <!-- sertifikat -->
  <div class="col-xs-12 certificate">
    <h3>
      Sertifikat
      <% if current_user.admin? %>
      <%= link_to 'Tambah Sertifikat', new_certificate_path,:class=>"pull-right btn btn-xs btn-primary",:id=>"add_certificate" ,:remote => true ,data: { disable_with: "Prosess...", id:"#{@employee.id}" } %>
      <% end %>
    </h3>
    <div class="certificate_add_content"></div>
    <%= render 'data_certificate' %>
  </div>
  <div class="col-xs-12">
    <a class="btn btn-primary" href="javascript:window.print()">Cetak</a>
  </div>
</div>


<div class="editor pull-right">
<% if admin? %>
  <%= link_to 'Edit', edit_employee_path(@employee) %> |
<% end %>
  <%= link_to 'Kembali', employees_path %>
</div>

app/views/employees/show.js.erb
console.log("show js men")