config/routes.rb
Rails.application.routes.draw do
  resources :permissions

  get 'presence/sync'

  get 'presence/report'

  get 'presence/details'

  get 'presence/stats'

  resources :machines

  get 'fingerprint/check'

  get 'fingerprint/syncronize'

  resources :time_tables

  resources :holidays

  get 'static_pages/dashboard'

  get 'static_pages/help'

  resources :divisions
  get 'add_division'        => 'divisions#add_division'
  post 'create_division'    => 'divisions#create_division'
  delete 'remove_division/:employee_id'  => 'division#remove_division'
  resources :letters

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  
  resources :news

  get 'sessions/new'

  get 'users/new'

  resources :entries

  resources :func_positions

  resources :inpassings

  resources :certificates

  resources :units

  resources :certifications

  resources :ranks

  resources :education_levels

  resources :groups

  resources :positions

  resources :users

  resources :employees do
    resources :educations
  end

  root                        'static_pages#dashboard'
  get 'help'              =>  'static_pages#help'
  get 'synclog'           =>  'static_pages#synclog'
  get 'synclog/:id'       =>  'static_pages#show_synclog',    as: :showlog

  get 'presence'          =>  'presence#index'
  get 'report'            =>  'presence#report'
  get 'details'           =>  'presence#details'
  get 'stats'             =>  'presence#stats'
  get 'self'              =>  'presence#self'

  get 'checkfp'           => 'fingerprint#check'
  get 'syncronize'        => 'fingerprint#syncronize'

  get   'signup'          =>  'users#new'
  get    'login'          =>  'sessions#new'
  post   'login'          =>  'sessions#create'
  delete 'logout'         =>  'sessions#destroy'

  get 'educations'        =>  'educations#all'

  

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
	mount_uploader :document, DocumentUploader
  
  	validates :theme, :presence=> {:message=> "kolom tema harus diisi"}
  	validates :year,:presence=>{:message=> "kolom tahun harus diisi"}
	belongs_to :employee

	def folder_name
		"sertifikat"
	end
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  respond_to :html
  respond_to :js

  def index
    @certificates = Certificate.all
    respond_with(@certificates)
  end

  def show
    respond_with(@certificate)
  end

  def new
    @title = "Tambah Sertifikat"
    @certificate = Certificate.new
    respond_with(@certificate)
  end

  def edit
    @title = "Edit Sertifikat"
  end

  def create

    @certificate = Certificate.new(certificate_params)
    respond_to do |format|
      if @certificate.save
        flash[:success] = "Data Sertifikat berhasil ditambah"
        format.html { redirect_to action: "index" }
        format.json { render action: 'index', status: :created, location: @unit }
        format.js
      else 
        flash[:error] = "Data Sertifikat gagal ditambah"
        format.html { respond_with(@unit) }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if  @certificate.update(certificate_params)
        flash[:success] = "Data Sertifikat berhasil diupdate"
        format.html { redirect_to action: "index" }
        # format.json { render action: 'index', status: :created, location: @unit }
        format.js
      else
        flash[:error] = "Data Sertifikat gagal diupdate"
        format.html {redirect_to action: "index"}
        format.js
      end
    end
    # respond_with(@certificate)
    
  end

  def destroy
    if   @certificate.destroy
      flash[:success] = "Data Sertifikat berhasil dihapus"
    else
      flash[:error] = "Data Sertifikat gagal dihapus"
    end
    respond_with(@certificate)
  end

  private
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    def certificate_params
      params.require(:certificate).permit(:employee_id, :theme, :year, :document)
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_data_created.html.erb
<tr id="certificate_<%= @certificate.id %>">
  <td><%= @certificate.employee.certificates.count %></td>
  <td><%= @certificate.employee.name.titleize %></td>
  <td><%= @certificate.theme %></td>
  <td><%= @certificate.year %></td>
  <td>
    <% if @certificate.document.present? %>
      <a href="<%= @certificate.document %>"target="_blank"style="color:green !important" target="_blank">Ada</a>
    <% else %>
      <div style="color:red">tidak ada</div>
    <% end %>
  </td>
  <td><%= link_to 'Edit', edit_certificate_path(@certificate),:class=>"edit edit_certificate",data: {remote: true,disable_with: "proses..."} %></td>
  <td><%= link_to 'Hapus', @certificate, method: :delete, data: { confirm: 'Ciyus mau di hapus?' },:class=>"destroy destroy_certificate", data: {remote: true, confirm: 'Ciyus mau di hapus?' ,disable_with: "proses..."} %></td>
</tr>

app/views/certificates/_error_messages.html.erb
<% if @certificate.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4>Ups! Ada <%= pluralize(@certificate.errors.count, "kesalahan") %> kesalahan yang membuat data anda tidak bisa didaftarkan</h4>
      <ul>
        <% @certificate.errors.messages.each do |message| %>
          <li><%= message.last.last.html_safe %></li>
        <% end %>
      </ul>
    </div>
<% end %>

	

app/views/certificates/_form.html.erb
<%= form_for(@certificate,:html => {:multipart => true}) do |f| %>
  <% if @certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
      <% @certificate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :employee_id, "Pilih Pegawai" %><br>
    <%= f.collection_select(:employee_id,Employee.all,:id,:name,{:prompt => 'pilih pegawai'}, :class=>"form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :theme,"Tema" %><br>
    <%= f.text_field :theme, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :year ,"Tahun"%><br>
    <%= f.date_select :year,:start_year=> 1995 , :class=>"form-control", :class=>"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :document, "Dokumen" %><br>
    <%= f.file_field :document,:class=> "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit "Simpan", :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/certificates/_form_remote.html.erb
<%= form_for(@certificate,:html => {:multipart => true},:remote=>true) do |f| %>

  <!-- <div class="form-group"> -->
  <%= f.hidden_field :employee_id,  :class=>"form-control"%>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="form-group">
    <%= f.label :theme,"Tema" %><br>
    <%= f.text_field :theme, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :year ,"Tahun"%><br>
    <%= f.date_select :year, :start_year=> 1995, :class=>"form-control", :class=>"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :document, "Dokumen" %><br>
    <%= f.file_field :document,:class=> "form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit "Simpan", :class=> "btn btn-primary",data: {disable_with: "Prosess..." }  %>
  </div>
<% end %>

app/views/certificates/_modal.html.erb
<div id="certificate_modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= @title || "Form" %></h4>
      </div>
      <div class="modal-body">
        <%= render 'form_remote' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">tutup</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/certificates/create.js.erb
pesan = "<div class=\"alert alert-success\" role=\"alert\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>Data sertifikat berhasil ditambah kakak!</div>"

<% if @certificate.errors.any? %>
	$("#certificate_modal form").prepend('<%= escape_javascript(render("error_messages", :formats => [:html])) %>');
<% else %>
	$('#certificate_modal').modal('hide')

	$('#certificateData tr:last').after("<%= j render('data_created') %>");

	$('.certificate_add_content').prepend(pesan)

<% end %>

app/views/certificates/destroy.js.erb
pesan = "<div class=\"alert alert-success\" role=\"alert\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>Data sertifikat berhasil hapus kakak!</div>";


$('.destroy_certificate').bind('ajax:success', function() {
   $(this).closest('tr').slideUp();
});

$('.certificate_add_content').prepend(pesan);

app/views/certificates/edit.html.erb
<h1>Edit Sertifikat</h1>

<%= render 'form' %>

<div class="pull-right">
	<%= link_to 'Show', @certificate %> |
<%= link_to 'Kembali', certificates_path %>
</div>

app/views/certificates/edit.js.erb
$('.certificate_add_content').html('<%= j render("modal") %>')

$('#certificate_modal').modal()

app/views/certificates/index.html.erb
<h1>Data Sertifikat</h1>

<table class="table">
  <thead>
    <tr>
      <th>No</th>
      <th>Pegawai</th>
      <th>Tema</th>
      <th>Tahun</th>
      <th>Dokumen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @no = 1 %>
    <% @certificates.each do |certificate| %>
      <tr>
        <td><%= @no %></td>
        <td><%= certificate.employee.name.titleize %></td>
        <td><%= certificate.theme %></td>
        <td><%= certificate.year %></td>
        <td>
          <% if certificate.document.present? %>
            <a href="<%= certification.document %>" target="_self"style="color:green">Ada</a>
          <% else %>
            <div style="color:red">tidak ada</div>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_certificate_path(certificate),:class=>"edit edit_certificate" %></td>
        <td><%= link_to 'Hapus', certificate, method: :delete, data: { confirm: 'Ciyus mau di hapus?' },:class=>"destroy destroy_certificate"  %></td>
      </tr>
      <% @no = @no + 1 %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Tambah Sertifikat', new_certificate_path %>

app/views/certificates/new.html.erb
<h1>Tambah Sertifikat</h1>

<%= render 'form' %>

<%= link_to 'Kembali', certificates_path,:class=>"pull-right" %>

app/views/certificates/new.js.erb
$('.certificate_add_content').html('<%= j render("modal") %>');

$('#certificate_modal').modal();

$('#add_certificate').bind('ajax:success', function() {
	id = $(this).data('id');
	console.log("Pegawai ID =>"+id)
	$('input#certificate_employee_id').val(id)
});

app/views/certificates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @certificate.employee_id %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @certificate.theme %>
</p>

<p>
  <strong>Year:</strong>
  <%= @certificate.year %>
</p>

<p>
  <strong>Document:</strong>
  <%= @certificate.document %>
</p>

<%= link_to 'Edit', edit_certificate_path(@certificate) %> |
<%= link_to 'Back', certificates_path %>

app/views/certificates/update.js.erb
pesan = "<div class=\"alert alert-success\" role=\"alert\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>Data sertifikat berhasil diupdate kakak!</div>"

modal = $('#certificate_modal');
data = $('#certificateData tr#certificate_<%= @certificate.id %>');

<% if @certificate.errors.any? %>
  $("#certificate_modal form").prepend('<%= escape_javascript(render("error_messages", :formats => [:html])) %>');
<% else %>
  data.children('td:nth-child(2)').html('<%= @certificate.employee.name %>');
  data.children('td:nth-child(3)').html('<%= @certificate.theme %>');
  data.children('td:nth-child(4)').html('<%= @certificate.year %>');
  data.children('td:nth-child(5)').html('<% if @certificate.document.present? %><a style=\"color:green !important" href="<%= @certificate.document_url %>" target="_blank">Ada</a><% else %><div style=\"color:red\">Tidak ada</div><% end %>');

  modal.modal('hide');
  $('.certificate_add_content').prepend(pesan);
<% end %>