config/routes.rb
Rails.application.routes.draw do
  resources :permissions

  get 'presence/sync'

  get 'presence/report'

  get 'presence/details'

  get 'presence/stats'

  resources :machines

  get 'fingerprint/check'

  get 'fingerprint/syncronize'

  resources :time_tables

  resources :holidays

  get 'static_pages/dashboard'

  get 'static_pages/help'

  resources :divisions
  get 'add_division'        => 'divisions#add_division'
  post 'create_division'    => 'divisions#create_division'
  delete 'remove_division/:employee_id'  => 'division#remove_division'
  resources :letters

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  
  resources :news

  get 'sessions/new'

  get 'users/new'

  resources :entries

  resources :func_positions

  resources :inpassings

  resources :certificates

  resources :units

  resources :certifications

  resources :ranks

  resources :education_levels

  resources :groups

  resources :positions

  resources :users

  resources :employees do
    resources :educations
  end

  root                        'static_pages#dashboard'
  get 'help'              =>  'static_pages#help'
  get 'synclog'           =>  'static_pages#synclog'
  get 'synclog/:id'       =>  'static_pages#show_synclog',    as: :showlog

  get 'presence'          =>  'presence#index'
  get 'report'            =>  'presence#report'
  get 'details'           =>  'presence#details'
  get 'stats'             =>  'presence#stats'
  get 'self'              =>  'presence#self'

  get 'checkfp'           => 'fingerprint#check'
  get 'syncronize'        => 'fingerprint#syncronize'

  get   'signup'          =>  'users#new'
  get    'login'          =>  'sessions#new'
  post   'login'          =>  'sessions#create'
  delete 'logout'         =>  'sessions#destroy'

  get 'educations'        =>  'educations#all'

  

end

app/models/education.rb
class Education < ActiveRecord::Base
	mount_uploader :document, DocumentUploader

 # t.string   "number"
 #    t.string   "graduate"
 #    t.date     "year"
 #    t.integer  "employee_id"
 #    t.datetime "created_at"
 #    t.datetime "updated_at"
 #    t.string   "document"
 #    t.integer  "education_level_id"
 #    t.string   "departement"

  validates :education_level_id, :presence => {:message=>"Jenjang pendidikan harus diisi"}
  validates :number, :presence => {:message=>"Nomor surat perjanjian dinas harus diisi"}
  validates :graduate, :presence => {:message=>"Nama unit pendidikan harus diisi"}
  validates :departement, :presence => {:message=>"Jurusan/program harus diisi"}

	belongs_to :employee
	belongs_to :education_level
	def folder_name
		"pendidikan"
	end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education,:set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html
  respond_to :js

  def index
    # @educations = Education.all
    @employee = Employee.find(params[:employee_id])
    @educations = @employee.educations

    respond_with(@educations)
  end

  def all
    @educations = Education.all
  end

  def show
    respond_with(@education)
  end

  def new
    @education = Education.new
    @employee = Employee.find(params[:employee_id])
    # respond_with(@education)
    respond_to do |format|
      format.html { respond_with(@education) }
      format.js #create.js.erb
    end
  end

  def edit
     @employee = Employee.find(params[:employee_id])
  end

  def create
    # @education = Education.new(education_params)
    # @education.save
    # respond_with(@education)
    @employee = Employee.find(params[:employee_id])
    @education = @employee.educations.create(education_params)
    @no = @employee.educations.count
    respond_to do |format|
      if @education.save
        format.html { redirect_to @employee, notice: 'Riwayat pendidikan berhasil ditambah' }
        format.json { render action: 'show', status: :created, location: @education }
        format.js #create.js.erb
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    @education.update(education_params)
    # respond_with(@education)
  end

  def destroy
    
    # respond_with(@education)
    respond_to do |format|
      if @education.destroy
        format.html { redirect_to @education.employee, notice: 'Riwayat pendidikan berhasil dihapus' }
        format.json { render action: 'show', status: :created, location: @education }
        format.js #create.js.erb
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  private
    def set_education
      @education = Education.find(params[:id])
    end

    def set_employee
      @empleoyee = Employee.find(params[:employee_id])
    end

    def education_params
      params.require(:education).permit(:number, :graduate, :year,:employee_id,:document,:education_level_id,:departement)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_data_created.html.erb
<tr id="education_<%= @education.id %>">      
  <td><%= @no%> </td>
  <td>
    <% if @education.education_level_id.present? %>
      <%= @education.education_level.name %>
    <% else %>
      -----
    <% end %>
  </td>
  
  <td><%= @education.number %></td>
  <td><%= @education.graduate %></td>
  <td><%= @education.departement %></td>
  <td><%= @education.year %></td>
  <td>
    <% if @education.document.present? %>
      <a href="<%= @education.document %>" target="_blank"style="color:green !important" data-image="<%= @education.document_url %>" >Ada</a>
    <% else %>
      <div style="color:red">Tidak ada</div>
    <% end %>
  </td>
  <td class="hide_print">
    <%= link_to 'Edit', edit_employee_education_path(@employee,@education) ,:class=>"edit edit_education",data: {remote: true,disable_with: "proses..."}%>
    <%= link_to 'Hapus', employee_education_path(@employee,@education), method: :delete, :class=>"destroy hapus_education",data: {remote: true, confirm: 'Ciyus mau di hapus?' ,disable_with: "proses..."} %></td>
  </td>
</tr>

app/views/educations/_education.html.erb
		<%= div_for education do %>
			<tr>
			  <td><%= @no%> </td>
		      <td><%= education.number %></td>
		      <td><%= education.graduate %></td>
		      <td><%= education.year %></td>
		      <td>
		        <% if education.document.present? %>
		          <div style="color:green">Ada</div>
		        <% else %>
		          <div style="color:red">Tidak ada</div>
		        <% end %>
		      </td>
      		</tr>
		<% end %>

app/views/educations/_error_messages.html.erb
<% if @education.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4>Ups! Ada <%= pluralize(@education.errors.count, "kesalahan") %> kesalahan yang membuat data anda tidak bisa didaftarkan</h4>
      <ul>

        <% @education.errors.messages.each do |attr,message| %>
          <li><%= message.split("").join("") %></li>
        <% end %>
      </ul>
    </div>
<% end %>

  

app/views/educations/_form.html.erb
<%= form_for [@employee,@education],:html => {:multipart => true},:remote=>true do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :education_level_id, "Jenjang Pendidikan" %>
    <%= f.collection_select(:education_level_id,EducationLevel.all,:id,:name,{:prompt => 'pilih jenjang'}, :class=>"form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :number,"Nomor Surat Perjanjian Dinas" %><br>
    <%= f.text_field :number,:class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :graduate ,"Nama Unit Pendidikan"%><br>
    <%= f.text_field :graduate,:class => "form-control"  %>
  </div>
   <div class="form-group">
    <%= f.label :departement ,"Jurusan/Program"%><br>
    <%= f.text_field :departement,:class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :year , "Tahun"%><br>
    <%= f.date_select :year ,:class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :document, "Dokumen" %>
    <%= f.file_field :document ,:class=>"form-control"%>
  </div>
  <div class="form-group">
    <% f.label :employee_id %> <br>
    <%= f.collection_select(:employee_id,Employee.all,:id,:name,{:prompt => 'pilih pegawai'}, :class=>"form-control")%>
  </div>
  <div class="actions">
    <%= f.submit "Simpan" ,:class=> "btn btn-primary"%>
  </div>
<% end %>

app/views/educations/_form_remote.html.erb
<%= form_for [@employee,@education],:html => {:multipart => true},:remote=>true do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :education_level_id, "Jenjang Pendidikan" %>
    <%= f.collection_select(:education_level_id,EducationLevel.all,:id,:name,{:prompt => 'pilih jenjang'}, :class=>"form-control",:required=>"required")%>
  </div>
  <div class="form-group">
    <%= f.label :number,"Nomor Surat Perjanjian Dinas" %><br>
    <%= f.text_field :number,:class => "form-control",:required=>"required" %>
  </div>
  <div class="form-group">
    <%= f.label :graduate ,"Nama Unit Pendidikan"%><br>
    <%= f.text_field :graduate,:class => "form-control" ,:required=>"required",:required=>"required" %>
  </div>
   <div class="form-group">
    <%= f.label :departement ,"Jurusan/Program"%><br>
    <%= f.text_field :departement,:class => "form-control" ,:required=>"required" %>
  </div>
  <div class="form-group">
    <%= f.label :year , "Tahun"%><br>
    <%= f.date_select :year ,:start_year=>1980,:end_year=>Date.today.year,:class => "form-control",:required=>"required" %>
  </div>
  <div class="form-group">
    <%= f.label :document, "Dokumen" %>
    <%= f.file_field :document ,:class=>"form-control" %>
  </div>
  <%= f.hidden_field :employee_id ,:class=>"form-control"%>
  <div class="actions">
    <%= f.submit "Simpan" ,:class=> "btn btn-primary"%>
  </div>
<% end %>

app/views/educations/_modal.html.erb
<div id="education_modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= @title || "Form" %></h4>
      </div>
      <div class="modal-body">
        <%= render 'form_remote' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">tutup</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/educations/all.html.erb
<h2>Data Pendidikan</h1>

<table class="table">
  <thead>
    <tr>
       <th>No</th>
        <th>Jenjang</th>
        <th>No Surat Perjanjian</th>
        <th>Unit Pendidikan</th>
        <th>Jurusan</th>
        <th>Tahun Lulus</th>
        <th>Arsip</th>
        <th>Pegawai</th>
        <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @no = 1 %>
    <% @educations.each do |education| %>

      <tr>  
        <td><%= @no %></td>
        <td>
          <% if education.education_level_id.present? %>
            <%= education.education_level.name %>
          <% else %>
            -----
          <% end %>
        </td>
        <td><%= education.number %></td>
        <td><%= education.graduate %></td>
        <td><%= education.departement %></td>
        <td><%= education.year %></td>
        <td>
          <% if education.document.present? %>
            <div style="color:green">Ada</div>
          <% else %>
            <div style="color:red">Tidak ada</div>
          <% end %>
        </td>
        <td><%= education.employee.name %></td>
        <td><%= link_to 'Tampil', employee_education_path(education.employee,education) %></td>
        <td><%= link_to 'Edit', edit_employee_education_path(education.employee,education) %></td>
        <td><%= link_to 'Hapus', employee_education_path(education.employee,education), method: :delete, data: { confirm: 'Ciyus mau di hapus??' } %></td>
      </tr>
      <% @no = @no +1 %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Tambah Pendidikan', new_employee_education_path(1) %>
</h2>

app/views/educations/create.js.erb
pesan = "<div class=\"alert alert-success\" role=\"alert\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>Data Pendidikan Berhasil ditambah kakak!</div>"

<% if @education.errors.any? %>
  $("#education_modal form").prepend('<%= escape_javascript(render("error_messages", :formats => [:html])) %>');
<% else %>
  $('#education_modal').modal('hide')
  $('#educationData tr:last').after("<%= j render('data_created') %>");
  $('#educationData').before(pesan)
<% end %>

app/views/educations/destroy.js.erb
pesan = "<div class=\"alert alert-success\" role=\"alert\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>Data Pendidikan Berhasil hapus kakak!</div>";


$('.hapus_education').bind('ajax:success', function() {
   $(this).closest('tr').slideUp();
});

$('#educationData').before(pesan);

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_educations_path %>

app/views/educations/new.html.erb
<h1>Tambah Pendidikan</h1>

<%= render 'form' %>

app/views/educations/new.js.erb
$('.education_add_content').html('<%= j render("modal") %>');

$('#education_modal').modal();

$('#add_education').bind('ajax:success', function() {
	id = $(this).data('id');
	console.log("Pegawai ID =>"+id)
	$('input#education_employee_id').val(id)
});


console.log("Add edu")

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nomor Surat:</strong>
  <%= @education.number %>
</p>

<p>
  <strong>Lulusan:</strong>
  <%= @education.graduate %>
</p>

<p>
  <strong>Tahun:</strong>
  <%= @education.year %>
</p>

<p>
  <strong>Pegawai :</strong>
  <%= @education.employee.name %>
</p>
<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>

app/views/educations/update.js.erb
pesan = "<div class=\"alert alert-success\" role=\"alert\"><button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>Data Pendidikan Berhasil diupdate kakak!</div>"
modal = $('#education_modal');
data = $('#educationData tr#education_<%= @education.id %>');

<% if @education.errors.any? %>
  $("#education_modal form").prepend('<%= escape_javascript(render("error_messages", :formats => [:html])) %>');
<% else %>
  data.children('td:nth-child(2)').html('<%= @education.education_level.name %>');
  data.children('td:nth-child(3)').html('<%= @education.number %>');
  data.children('td:nth-child(4)').html('<%= @education.graduate %>');
  data.children('td:nth-child(5)').html('<%= @education.departement %>');
  data.children('td:nth-child(6)').html('<%= @education.year %>');
   data.children('td:nth-child(7)').html('<% if @education.document.present? %><a style=\"color:green !important" href="<%= @education.document_url %>" target="_self">Ada</a><% else %><div style=\"color:red\">Tidak ada</div><% end %>');

  modal.modal('hide');
  $('#educationData').before(pesan);
<% end %>

  



// modal.remove();